### ISSUE TITLE
coolie.js 调用webuploader.js 无法创建实例

### ISSUE THREAD

**Issue by Chinalink** [cooliejs/coolie.js#13]
define(function(require,exports,module){
        require('../lib/juqery/jquery.min.js');
	require('../lib/webuploader/webuploader.html5only.min.js');
	require('../lib/webuploader/webuploader.css','css|url');
	
//	require('jquery');
//	require('webuploader');
	
	var fileBtn;
	
	function uploader(container){
		this.container = $(container);
	}
	
	module.exports = uploader;
	
	uploader.prototype.render = function(){
		this._uploader();
	}
	
	uploader.prototype._uploader = function(){
		
		var container = this.container;
		
		$(container).each(function(){
				var $list = $(this).siblings('.uploader-list');
				// 初始化Web Uploader
				var uploader = new WebUploader.Uploader({
				    // 选完文件后，是否自动上传。
				    auto: true,
				    // 文件接收服务端。
				    server:'http://webuploader.duapp.com/server/fileupload.php',
				    // 选择文件的按钮。可选。
				    // 内部根据当前运行是创建，可能是input元素，也可能是flash.
				   	pick: this,
	                //可以上传同样的文件
	                duplicate : true,
				    // 只允许选择图片文件。
				    accept: {
				        title: 'Images',
				        extensions: 'gif,jpg,jpeg,bmp,png',
				        mimeTypes: 'image/*'
				    },
				    //单个文件大小2M
				    fileSingleSizeLimit:2*1024*1024
				});
                      ...
});
		
	}
	
})

用coolie 加载jquery和webuploader（在外层加了define(function(require,exports,module){})包装）。用google看，Network加载没有问题。但是报（Uncaught ReferenceError: WebUploader is not defined）
// 初始化Web Uploader
var uploader = new WebUploader.Uploader 

如果代码不变，仅仅换为sea.js加载，就不会报错，可以正常运行，求问这是怎么回事？

**Comment by cloudcome** [comment]
![image](https://cloud.githubusercontent.com/assets/3362033/13308581/77ad7e4e-dbaf-11e5-8ebe-536303e3fe07.png)

- 开发环境下，一个文件一个模块
- 开发环境下，不需要写模块 ID

coolie.js 相对于 seajs 对模块的规范更加严格，如果要适配 coolie.js 的话，需要修改源代码。
