### ISSUE TITLE
how to set babel in a project which was compiled by coolie ?

### ISSUE THREAD

**Issue by Hellowor1d** [cooliejs/coolie.js#15]
hi~ 
we had used coolie as the compile tool. recently , we will upgrade the project , and es6 is really the direction face to future, so how to set babel work with coolie ?
 Thanks~

**Comment by cloudcome** [comment]
你可以实时编译 es6 的文件，就像实时编译 scss 文件一样。然后 coolie 还是和之前一样，构建的是原生 js、css。
